---
- name: Configure virtual router interfaces
  hosts: routers
  gather_facts: no

  tasks:
    - name: Configure Loopback interface
      ios_config:
        lines:
          - description Configured by Ansible (An2)
          - ip address 10.200.200.1 255.255.255.255
        parents: interface Loopback200
