---
    - name: AUTOMATIC BACKUP OF RUNNING-CONFIG
      hosts: routers
      gather_facts: false
      connection: local
      tasks:
        - name: GET RUNNING CONFIG
          ios_command:
            commands:
              - show running-config
          register: config
    
        - name: SAVE CONFIG
          copy:
            content: "{{ config.stdout[0] }}"
            dest: "backups/show_run_{{ inventory_hostname }}.txt"
    