---
    - name: CONFIGURE IPv6 ADDRESSING
      hosts: CSR1kv
      gather_facts: false
      connection: local
      tasks:
        - name: CONFIGURE IPV6 ON GIG1
          ios_config:
            parents: "interface GigabitEthernet1"
            lines:
              - description IPv6 ADDRESS
              - ipv6 address 2001:DB8:ACAD:1::1/64
              - ipv6 address FE80::1:1 link-local
    
        - name: SHOW IPV6 INTERFACE
          ios_command:
            commands:
              - show ipv6 interface brief
          register: output
    
        - name: SAVE OUTPUT
          copy:
            content: "{{ output.stdout[0] }}"
            dest: "ios_configurations/IPv6_output_{{ inventory_hostname }}.txt"
    