---
- name: Nginx webserver experiment
  hosts: nginxservers
  become: yes

  vars:
    nginx_port: 8082

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: latest

    - name: Configure Nginx listen port (safe)
      replace:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen\s+80\s+default_server;'
        replace: '    listen {{ nginx_port }} default_server;'
      notify: Restart Nginx

    - name: Configure Nginx listen port ipv6 (safe)
      replace:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen\s+\[::\]:80\s+default_server;'
        replace: '    listen [::]:{{ nginx_port }} default_server;'
      notify: Restart Nginx

    - name: Deploy custom index.html
      copy:
        src: templates/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"

    - name: Ensure Nginx is enabled and running
      service:
        name: nginx
        enabled: yes
        state: started

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
